version: 2

updates:
  - package-ecosystem: "npm"
    directory: "/"
    schedule:
      interval: "daily"
    groups:
      slice-machine:
        patterns:
          - "@slicemachine/*"
          - "slice-machine-ui"
